/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dualboot_engine_EngineInterface */

#ifndef _Included_com_dualboot_engine_EngineInterface
#define _Included_com_dualboot_engine_EngineInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    AddBitmapData
 * Signature: (ILjava/lang/String;Ljava/nio/ByteBuffer;III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_AddBitmapData
  (JNIEnv *, jclass, jint, jstring, jobject, jint, jint, jint);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    Destroy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dualboot_engine_EngineInterface_Destroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    GetNeedsReload
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_GetNeedsReload
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    LoadFile
 * Signature: (ILandroid/content/res/AssetManager;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_dualboot_engine_EngineInterface_LoadFile
  (JNIEnv *, jclass, jint, jobject, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    LoadResources
 * Signature: (ILandroid/content/res/AssetManager;)I
 */
JNIEXPORT jint JNICALL Java_com_dualboot_engine_EngineInterface_LoadResources
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    Recreate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_dualboot_engine_EngineInterface_Recreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceCameraSet
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceCameraSet
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceEnvironment
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceEnvironment
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceFontMessage
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceFontMessage
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceModelSwap
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceModelSwap
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceModelToggle
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceModelToggle
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceTextureGroup
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceTextureGroup
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceTimeOfDay
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceTimeOfDay
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceTimeOfDayAuto
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceTimeOfDayAuto
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetPreferenceUserImage
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetPreferenceUserImage
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    SetStateLocation
 * Signature: (IFF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_SetStateLocation
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    Sleep
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_dualboot_engine_EngineInterface_Sleep
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_dualboot_engine_EngineInterface
 * Method:    Update
 * Signature: (IIIFFJDFZ)I
 */
JNIEXPORT jint JNICALL Java_com_dualboot_engine_EngineInterface_Update
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jlong, jdouble, jfloat, jboolean);

#ifdef __cplusplus
}
#endif
#endif
