# Exercise the actual CLI, filename mapping and successful PAM serialization.
# Only remove the randomly named test directory created by this invocation.
string(RANDOM LENGTH 20 ALPHABET abcdefghijklmnopqrstuvwxyz suffix)
set(output "${TEST_OUTPUT}/export-test-${suffix}")
if(EXISTS "${output}")
  message(FATAL_ERROR "Test output unexpectedly exists")
endif()
file(MAKE_DIRECTORY "${output}")
execute_process(COMMAND "${INSPECTOR}" "${ASSETS}" --export-pam "${output}"
  RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
  file(REMOVE_RECURSE "${output}")
  message(FATAL_ERROR "Export failed: ${errors}")
endif()

file(GLOB inputs "${ASSETS}/tex/*.pvr")
file(GLOB exports "${output}/*.pam")
list(LENGTH exports count)
set(failure "")
if(NOT count EQUAL 100)
  set(failure "Expected 100 PAM files, found ${count}")
endif()
foreach(input IN LISTS inputs)
  get_filename_component(stem "${input}" NAME_WE)
  if(NOT EXISTS "${output}/${stem}.pam")
    set(failure "Missing export for ${stem}")
  endif()
endforeach()

# Independently inspected original fixtures: both are 2x2 RGB565.
# white has four 0xffff pixels; redlight has four 0x9820 pixels.
string(HEX "P7\nWIDTH 2\nHEIGHT 2\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n" header)
foreach(stem white redlight)
  if(EXISTS "${output}/${stem}.pam")
    file(READ "${output}/${stem}.pam" actual HEX)
    if(stem STREQUAL "white")
      string(REPEAT "ffffffff" 4 pixels)
    else()
      string(REPEAT "9c0400ff" 4 pixels)
    endif()
    if(NOT actual STREQUAL "${header}${pixels}")
      set(failure "Incorrect PAM header/pixels for ${stem}")
    endif()
  endif()
endforeach()
file(REMOVE_RECURSE "${output}")
if(NOT failure STREQUAL "")
  message(FATAL_ERROR "${failure}")
endif()
