string(RANDOM LENGTH 20 ALPHABET abcdefghijklmnopqrstuvwxyz suffix)
set(output "${TEST_OUTPUT}/render-test-${suffix}")
if(EXISTS "${output}")
  message(FATAL_ERROR "Test output unexpectedly exists")
endif()
file(MAKE_DIRECTORY "${output}")
execute_process(COMMAND "${TESTER}" --write-render-fixture "${output}" RESULT_VARIABLE result)
if(result EQUAL 0)
  execute_process(COMMAND "${RENDERER}" "${output}" "${output}/frame.pam" 0 64 64 RESULT_VARIABLE result)
endif()
if(result EQUAL 0)
  execute_process(COMMAND "${TESTER}" --check-frame "${output}/frame.pam" RESULT_VARIABLE result)
endif()
if(result EQUAL 0)
  execute_process(COMMAND "${TESTER}" --write-invisible-fixture "${output}" RESULT_VARIABLE result)
endif()
if(result EQUAL 0)
  execute_process(COMMAND "${RENDERER}" "${output}" "${output}/frame.pam" 0 64 64 RESULT_VARIABLE result)
endif()
if(result EQUAL 0)
  execute_process(COMMAND "${TESTER}" --check-invisible-frame "${output}/frame.pam" RESULT_VARIABLE result)
endif()
file(REMOVE_RECURSE "${output}")
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Native renderer fixture failed")
endif()
